### ISSUE TITLE
Select specific sound device for the audio output

### ISSUE THREAD

**Issue by Iraito** [piercecohen1/AI-TTS#1]
I checked the code but the pygame part of it for the initialization of the sound devices left me puzzled, can i get some explanation on how to choose a specific sound output?

**Comment by piercecohen1** [comment]
@Iraito I hadn't thought to implement different audio output devices, but will look into this.

Since it does not specify a particular sound output device, the default output device is used. Can you confirm whether playback is working for you on your default output device?

**Comment by Iraito** [comment]
The default one works, for streaming a specific output would be wonderful.

**Comment by Iraito** [comment]
In the meantime i was able to get my custom output by changing the pygame.init() line to pygame.mixer.init(devicename= 'MY DEVICE')

Hopefully this will be useful to someone else stumbling upon this issue.

To get the devices list the command "python3 -m sounddevice" can be used after installing the sounddevice module in python

**Comment by piercecohen1** [comment]
I will definitely look into a better way to implement this in the future. Going to close this issue for the time-being but thank you for the feedback!
