### ISSUE TITLE
[Errno 2] No such file or directory: 'afplay'

### ISSUE THREAD

**Issue by idealdeal** [piercecohen1/AI-TTS#2]
Running the command `python TTS.py -v pNInz6obpgDQGcFmaJgB -a -t "hello world"` spits out the error message `[Errno 2] No such file or directory: 'afplay'`

**Comment by piercecohen1** [comment]
I just updated the repo to add Windows support. Can you try pulling the repo again and trying the same command?

```
git clone https://github.com/piercecohen1/AI-TTS.git
pip install -r requirements.txt
```

Please let me know if it works for you now.

**Comment by idealdeal** [comment]
Issue has been fixed. The problem was with the line https://github.com/piercecohen1/AI-TTS/blob/60141df0790db0ec2656943804b2b444b02268a7/TTS.py#LL111C17-L111C61

which was basically calling a `afplay` media player, which I didn't have under Linux. After changing it to `mpv`, the script worked.

**Comment by piercecohen1** [comment]
Great. I updated the `develop` branch to use mpv for Linux playback. Can run the following command to pull that branch of the repo and confirm it is working for you? If so, I will merge the changes onto `main`
```
git clone -b develop https://github.com/piercecohen1/AI-TTS.git
```

**Comment by idealdeal** [comment]
`develop` works! Feel free to merge.

**Comment by piercecohen1** [comment]
Thanks for reporting!
